In [2]:
import numpy as np
import pandas as pd

In [112]:
a=np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [24]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [26]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [28]:
a.reshape(1,12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a.reshape(2,-1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
a.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
a.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [30]:
# Массив из одного столбца и 12 строк является двумерным

In [36]:
b=np.random.randn(3,4)
b

array([[-0.96822706, -0.34881406,  0.12924971,  2.64010935],
       [-0.75216249, -0.98903621,  1.7902908 ,  0.39365444],
       [-0.81247047,  1.71776193,  0.65894548, -0.13177985]])

In [40]:
b.size

12

In [41]:
b1=b.flatten()
b1.size

12

In [47]:
a=np.arange(20,0,-2)
a.shape

(10,)

In [49]:
b=a.reshape(1,10)
b.shape

(1, 10)

In [50]:
# Разница в том, что массив 'а' одномерный, а массив 'b' двумерный

In [62]:
a=np.zeros((2,2)) 
b=np.ones((3,2)) 
v=np.vstack((a,b)) 
v.size

10

In [110]:
a=np.arange(0,12)
A=a.reshape(4,3)
At=A.T
B=np.dot(A,At)
B
np.linalg.det(B)

0.0

In [72]:
# Для данной матрицы В не получится вычислить обратную матрицу, т.к. определитель матрицы В = 0, а это означает, что матрица вырожденная

In [111]:
np.random.seed(42)
c=np.random.randint(0,16,16)
C=c.reshape(4,4)
D=np.add(C*10,B)
np.linalg.det(D)

-28511999.999999944

In [83]:
np.linalg.matrix_rank(D)

4

In [85]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [97]:
D_inv[D_inv[:,:]<0]=0
D_inv[D_inv[:,:]>0]=1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [106]:
E=np.where((D_inv[:,:]==1),B,C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])